// import { getRandomBetween } from "./utils";

 const films = [
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
  {
    title: 'bla',
    releaseDate: '01/01/2001',
    plot: 'Lorem ipsum',
    poster: `./images/posters/jurassic-world.jpg`,
    boxOffice: getRandomBetween(300000, 600000) ,
    rating: getRandomBetween(1, 10),
    director: 'Christopher Nolan',
  },
];
